ignore_table_names: false
table_mappings:
- source: source
  destination: dest
  enabled: true
attribute_mappings:
- source: name
  target: name
  enabled: true
  compare: true
- source: type
  target: datatype
  enabled: true
  compare: true
- source: allowNulls
  target: nullable
  enabled: true
  compare: false
- source: description
  target: comment
  enabled: true
  compare: true
- source: default
  target: default
  enabled: true
  compare: true
- source: displayFormat
  target: display_format
  enabled: true
  compare: true
- source: length
  target: size
  enabled: true
  compare: true
- source: nullable
  target: nullable
  enabled: true
  compare: false
ignored_attributes: []
missing_attribute:
  severity: WARNING
  fail: false
xml:
  enabled: true
  object_type: DataSource
  validate_object_types:
  - DataSource:field
  validate_scope: selected_objects
  missing_attribute:
    severity: WARNING
    fail: false
value_mappings:
- attribute: datatype
  source: TEXT
  target: VARCHAR
  enabled: true
- attribute: datatype
  source: STRING
  target: VARCHAR
  enabled: true
- attribute: datatype
  source: CHAR
  target: VARCHAR
  enabled: true
- attribute: datatype
  source: NUMBER
  target: NUMERIC
  enabled: true
- attribute: datatype
  source: INTEGER
  target: NUMERIC
  enabled: true
- attribute: datatype
  source: INT
  target: NUMERIC
  enabled: true
- attribute: datatype
  source: FLOAT
  target: NUMERIC
  enabled: true
- attribute: datatype
  source: DOUBLE
  target: NUMERIC
  enabled: true
